[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'
fs_permissions = [{ access = "read", path = "./test/NukeFund/merkle_data.json"}]

[invariant]
runs = 1000
depth = 18
fail_on_revert = true